import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowLeft,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {useI18n,displayName,systemDescription,systemName,structureExplanation,hasOwnExplanation,searchText} from './i18n';
type NavEntry={chosen:(Concept&{partId?:string})|null;panel:'layers'|'search'|null};
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const {lang,setLang,t}=useI18n();
 const viewLabel=(v:View)=>v==='three-quarter'?t('viewThreeQuarter'):v==='front'?t('viewFront'):v==='side'?t('viewSide'):t('viewBack');
 const chosenTitle=(c:(Concept&{partId?:string})|null)=>c?displayName(lang,{id:c.partId??c.id,name:c.name}):'';
 const backLabel=nav.length>0&&!nav[nav.length-1].chosen&&nav[nav.length-1].panel==='search'?t('backToSearch'):t('back');
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<(Concept&{partId?:string})|null>(null),[composing,setComposing]=useState(false),[nav,setNav]=useState<NavEntry[]>([]);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error(t('errorCatalogue'));return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!e.isComposing&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const lastResults=useRef<Concept[]>([]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const detailText=chosen&&selected?(lang==='zh'?structureExplanation(lang,chosen.id,systemDescription(lang,selected.system,'')):explanation(chosen.name,selected.system)):'';
 const ownExplanation=chosen?hasOwnExplanation(lang,chosen.id,chosen.name,EXPLANATIONS):false;
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(composing)return lastResults.current;if(!atlas)return[];const term=query.toLowerCase().trim();if(!term){const picked=['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);lastResults.current=picked;return picked;}const matched=atlas.concepts.filter(c=>searchText(lang,c).includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>displayName(lang,a).length-displayName(lang,b).length).slice(0,80);lastResults.current=matched;return matched;},[atlas,query,lang,composing]);
 const choose=(c:Concept)=>{setNav(h=>[...h,{chosen,panel}]);setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)),lang);},[atlas,lang]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setNav(h=>[...h,{chosen,panel}]);setChosen({id:p.conceptId,name:p.name,elements:[id],partId:id});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const goBack=()=>{setNav(h=>{const prev=h[h.length-1];if(!prev)return h;setChosen(prev.chosen);setDetails(prev.panel?false:!!prev.chosen);setPanel(prev.panel);setState(s=>({...s,selected:prev.chosen?.elements??[],isolate:false}));return h.slice(0,-1);});};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setNav([]);setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} lang={lang} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {t('brandEyebrow')}</div><h1>{t('brandTitle')}<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{t('modeledPieces',{n:atlas?atlas.parts.length.toLocaleString():'2,234'})} <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label={t('explorerPanels')}><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t('searchAnatomy')}><Search size={18}/><span>{t('findStructure')}</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button lang-switch" aria-label={t('switchLanguage')} title={t('switchLanguage')} onClick={()=>setLang(lang==='zh'?'en':'zh')}>{lang==='zh'?'EN':'中'}</Button><Button variant="ghost" className="icon-button" aria-label={t('aboutAtlas')} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={t('systems')}>
   <div className="panel-heading"><span>{t('systems')}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t('closeSystems')}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t('presetAll')}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t('presetSkeleton')}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t('presetOrgans')}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={t('showOnly',{name:systemName(lang,s.id,s.name)})} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{systemName(lang,s.id,s.name)}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={t('showSystem',{name:systemName(lang,s.id,s.name)})} /></div>)}</div>
   <div className="panel-foot"><span>{t('piecesVisible',{n:visibleCount.toLocaleString()})}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t('hideAll')}</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label={t('findAnatomy')}><div className="panel-heading"><span>{t('findStructure')}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t('closeSearch')}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>displayName(lang,c)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={t('searchPlaceholder')} aria-label={t('searchAria')} showTrigger={false} onCompositionStart={()=>setComposing(true)} onCompositionEnd={(e)=>{setComposing(false);setQuery(e.currentTarget.value);}}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t('searchEmpty')}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{displayName(lang,c)}</span><span className="small-number">{t('pieces',{n:c.elements.length})}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t('searchNoteRefine'):t('searchNoteStart')}</p></section>}
  <nav className="view-controls glass" aria-label={t('cameraControls')}>{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={viewLabel(v)} aria-label={viewLabel(v)}><span>{lang==='zh'?['¾','正','侧','背'][i]:['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?t('pauseRotation'):t('rotateBody')} title={t('autoRotate')} className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label={t('resetView')} title={t('reset')} onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?chosenTitle(chosen):t('captionSelected')):state.explode>.95?t('captionInventory'):state.explode>.05?t('captionSeparated'):t('captionDefault')}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t('openSystemLayers')}><Layers3 size={20}/><span>{t('systems')}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t('explodeAnatomy')}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t('endpointAssembled')}</span><span>{t('endpointEveryPiece')}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t('assembleReset')}><RotateCcw size={18}/><span>{t('reset')}</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?t('dragPan'):t('dragOrbit')} <b>·</b> {t('pinchZoom')} <b>·</b> {t('tapInspect')}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t('sourceCredits')} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t('loadingTitle')}</strong><span>{t('loadingDetail',{n:progress,m:atlas?.parts.length.toLocaleString()??'2,234'})}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>{t('reloadViewer')}</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?systemName(lang,system.id,system.name):t('anatomyFallback')}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosenTitle(chosen)}</SheetTitle></div>{nav.length>0&&<Button variant="ghost" className="detail-back" onClick={goBack}><ArrowLeft size={15}/><span>{backLabel}</span></Button>}<div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{detailText}</SheetDescription>{chosen&&!ownExplanation&&<span className="context-note">{t('systemOverviewNote')}</span>}<div className="structure-meta"><span>{t('atlasReference')}<strong>{chosen?.id}</strong></span><span>{t('selectedPieces')}<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{t('includedStructures')}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{displayName(lang,p)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{t('morePieces',{n:selectedParts.length-50})}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t('viewSource')} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t('showSurrounding'):t('isolateStructure')}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setNav([]);setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t('clearSelection')}</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">{t('aboutEyebrow')}</div><SheetTitle className="structure-title">{t('aboutTitle')}</SheetTitle><SheetDescription>{t('aboutLead')}</SheetDescription><div className="about-copy"><p><strong>{t('aboutScopeLabel')}</strong><br/>{t('aboutScopeBody')}</p><p>{t('aboutCaveat')}</p><p>{t('aboutDesign')}</p><h3>{t('aboutSourceHeading')}</h3><p>{t('aboutLicense')}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t('aboutLicenseLink')} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t('aboutSourceLink')} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t('aboutPublicationLink')} <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
