# -*- coding: utf-8 -*-
"""解剖学术语英中词表。type: mod=方位/序数/修饰, n=结构名词, m=肌名（需后置）"""

M = 'mod'
N = 'n'
MU = 'm'

W = {
# ===== 方位 / 序数 / 修饰 =====
'left': ('左', M), 'right': ('右', M), 'bilateral': ('双侧', M),
'anterior': ('前', M), 'posterior': ('后', M), 'superior': ('上', M), 'inferior': ('下', M),
'medial': ('内侧', M), 'lateral': ('外侧', M), 'intermediate': ('中间', M), 'middle': ('中', M),
'central': ('中央', M), 'deep': ('深', M), 'superficial': ('浅', M),
'proximal': ('近侧', M), 'distal': ('远侧', M), 'upper': ('上', M), 'lower': ('下', M),
'internal': ('内', M), 'external': ('外', M), 'common': ('总', M), 'proper': ('固有', M),
'major': ('大', M), 'minor': ('小', M), 'magnus': ('大', M), 'maximus': ('最大', M),
'minimus': ('最小', M), 'medius': ('中间', M), 'longus': ('长', M), 'brevis': ('短', M),
'longissimus': ('最长', M), 'major': ('大', M),
'first': ('第一', M), 'second': ('第二', M), 'third': ('第三', M), 'fourth': ('第四', M),
'fifth': ('第五', M), 'sixth': ('第六', M), 'seventh': ('第七', M), 'eighth': ('第八', M),
'ninth': ('第九', M), 'tenth': ('第十', M), 'eleventh': ('第十一', M), 'twelfth': ('第十二', M),
'primary': ('初级', M), 'secondary': ('次级', M), 'tertiary': ('三级', M),
'dorsal': ('背侧', M), 'ventral': ('腹侧', M), 'palmar': ('掌侧', M), 'plantar': ('足底', M),
'transverse': ('横', M), 'oblique': ('斜', M), 'longitudinal': ('纵', M), 'vertical': ('垂直', M),
'accessory': ('副', M), 'rudimentary': ('退化', M), 'atrial': ('心房', M), 'ventricular': ('心室', M),
'apical': ('尖', M), 'basal': ('基底', M), 'cortical': ('皮质', M), 'medullary': ('髓质', M),
'segmental': ('段', M), 'basilar': ('基底', M), 'mammillary': ('乳头', M), 'lumbrical': ('蚓状', M),
'little': ('小', M), 'index': ('示指', M), 'ring': ('环状', M), 'great': ('大', M),
'lesser': ('小', M), 'greater': ('大', M), 'true': ('真', M), 'false': ('假', M),
'fibrous': ('纤维', M), 'bony': ('骨性', M), 'muscular': ('肌性', M), 'membranous': ('膜性', M),
'osseous': ('骨性', M), 'cartilaginous': ('软骨性', M), 'serous': ('浆膜', M), 'mucous': ('黏膜', M),

# ===== 通用结构名词 =====
'artery': ('动脉', N), 'arteries': ('动脉', N), 'vein': ('静脉', N), 'veins': ('静脉', N),
'nerve': ('神经', N), 'nerves': ('神经', N), 'muscle': ('肌', N), 'muscles': ('肌', N),
'bone': ('骨', N), 'bones': ('骨', N), 'cartilage': ('软骨', N), 'cartilages': ('软骨', N),
'ligament': ('韧带', N), 'ligaments': ('韧带', N), 'tendon': ('腱', N), 'tendons': ('腱', N),
'joint': ('关节', N), 'joints': ('关节', N), 'fascia': ('筋膜', N), 'retinaculum': ('支持带', N),
'sheath': ('鞘', N), 'bursa': ('囊', N), 'capsule': ('囊', N), 'membrane': ('膜', N),
'vertebra': ('椎骨', N), 'vertebrae': ('椎骨', N), 'rib': ('肋', N), 'ribs': ('肋', N),
'sternum': ('胸骨', N), 'clavicle': ('锁骨', N), 'scapula': ('肩胛骨', N),
'humerus': ('肱骨', N), 'radius': ('桡骨', N), 'ulna': ('尺骨', N), 'femur': ('股骨', N),
'tibia': ('胫骨', N), 'fibula': ('腓骨', N), 'patella': ('髌骨', N),
'phalanx': ('指骨', N), 'phalanges': ('指骨', N), 'metacarpal': ('掌骨', N), 'metacarpals': ('掌骨', N),
'metatarsal': ('跖骨', N), 'metatarsals': ('跖骨', N), 'carpal': ('腕骨', N), 'carpals': ('腕骨', N),
'tarsal': ('跗骨', N), 'tarsals': ('跗骨', N), 'talus': ('距骨', N), 'calcaneus': ('跟骨', N),
'sacrum': ('骶骨', N), 'coccyx': ('尾骨', N), 'mandible': ('下颌骨', N), 'maxilla': ('上颌骨', N),
'hyoid': ('舌骨', N), 'vomer': ('犁骨', N), 'palatine': ('腭骨', N), 'zygomatic': ('颧骨', N),
'lacrimal': ('泪骨', N), 'nasal': ('鼻骨', N), 'ethmoid': ('筛骨', N), 'sphenoid': ('蝶骨', N),
'frontal': ('额骨', N), 'parietal': ('顶骨', N), 'occipital': ('枕骨', N), 'temporal': ('颞骨', N),
'lobe': ('叶', N), 'lobes': ('叶', N), 'segment': ('段', N), 'segments': ('段', N),
'part': ('部', N), 'parts': ('部', N), 'portion': ('部', N), 'portions': ('部', N),
'branch': ('支', N), 'branches': ('支', N), 'trunk': ('干', N), 'trunks': ('干', N),
'tree': ('树', N), 'root': ('根', N), 'roots': ('根', N), 'body': ('体', N), 'bodies': ('体', N),
'head': ('头', N), 'heads': ('头', N), 'neck': ('颈', N), 'base': ('底', N), 'apex': ('尖', N),
'arch': ('弓', N), 'arches': ('弓', N), 'ring': ('环', N), 'disk': ('盘', N), 'disc': ('盘', N),
'wall': ('壁', N), 'walls': ('壁', N), 'cavity': ('腔', N), 'cavities': ('腔', N),
'surface': ('面', N), 'surfaces': ('面', N), 'margin': ('缘', N), 'margins': ('缘', N),
'border': ('缘', N), 'angle': ('角', N), 'angles': ('角', N), 'process': ('突', N), 'processes': ('突', N),
'foramen': ('孔', N), 'foramina': ('孔', N), 'canal': ('管', N), 'canals': ('管', N),
'duct': ('管', N), 'ducts': ('管', N), 'sinus': ('窦', N), 'sinuses': ('窦', N),
'sulcus': ('沟', N), 'sulci': ('沟', N), 'gyrus': ('回', N), 'gyri': ('回', N),
'fissure': ('裂', N), 'fissures': ('裂', N), 'notch': ('切迹', N), 'fossa': ('窝', N),
'cortex': ('皮质', N), 'medulla': ('髓质', N), 'nucleus': ('核', N), 'nuclei': ('核', N),
'tract': ('束', N), 'tracts': ('束', N), 'peduncle': ('脚', N), 'peduncles': ('脚', N),
'ganglion': ('神经节', N), 'ganglia': ('神经节', N), 'plexus': ('丛', N),
'lamina': ('板', N), 'laminae': ('板', N), 'plate': ('板', N), 'cortex': ('皮质', N),
'cell': ('细胞', N), 'cells': ('细胞', N), 'fibre': ('纤维', N), 'fiber': ('纤维', N),
'fiber': ('纤维', N), 'fibers': ('纤维', N), 'fibres': ('纤维', N),
'zone': ('区', N), 'zones': ('区', N), 'region': ('区', N), 'regions': ('区', N),
'area': ('区', N), 'areas': ('区', N), 'field': ('区', N), 'division': ('分支', N),
'subdivision': ('亚区', N), 'subdivisions': ('亚区', N), 'set': ('组', N), 'sets': ('组', N),
'tributary': ('属支', N), 'tributaries': ('属支', N), 'ramus': ('支', N), 'rami': ('支', N),
'orifice': ('口', N), 'opening': ('口', N), 'aperture': ('口', N), 'hiatus': ('裂孔', N),
'valve': ('瓣', N), 'valves': ('瓣', N), 'cusp': ('瓣尖', N), 'cusps': ('瓣尖', N),
'leaflet': ('叶', N), 'leaflets': ('叶', N), 'septum': ('隔', N), 'septa': ('隔', N),
'atrium': ('心房', N), 'ventricle': ('心室', N), 'auricle': ('心耳', N),
'myocardium': ('心肌', N), 'endocardium': ('心内膜', N), 'pericardium': ('心包', N),
'arteriole': ('小动脉', N), 'venule': ('小静脉', N), 'capillary': ('毛细血管', N),
'bone': ('骨', N), 'organ': ('器官', N), 'organs': ('器官', N), 'structure': ('结构', N),
'structure': ('结构', N), 'substance': ('质', N), 'tissue': ('组织', N), 'tissues': ('组织', N),
'skin': ('皮肤', N), 'gland': ('腺', N), 'glands': ('腺', N), 'node': ('结', N), 'nodes': ('结', N),
'papilla': ('乳头', N), 'papillae': ('乳头', N), 'ductule': ('小管', N), 'tubule': ('小管', N),
'fluid': ('液', N), 'space': ('间隙', N), 'spaces': ('间隙', N), 'compartment': ('区室', N),
'layer': ('层', N), 'layers': ('层', N), 'column': ('柱', N), 'columna': ('柱', N),
'band': ('带', N), 'bands': ('带', N), 'stripe': ('纹', N), 'line': ('线', N), 'lines': ('线', N),
'point': ('点', N), 'territory': ('区', N), 'system': ('系统', N), 'systems': ('系统', N),

# ===== 部位 / 器官形容词 =====
'gastric': ('胃', N), 'hepatic': ('肝', N), 'renal': ('肾', N), 'splenic': ('脾', N),
'pancreatic': ('胰', N), 'intestinal': ('肠', N), 'colic': ('结肠', N), 'caecal': ('盲肠', N),
'cecal': ('盲肠', N), 'ileal': ('回肠', N), 'jejunal': ('空肠', N), 'duodenal': ('十二指肠', N),
'oesophageal': ('食管', N), 'esophageal': ('食管', N), 'tracheal': ('气管', N),
'bronchial': ('支气管', N), 'pulmonary': ('肺', N), 'pleural': ('胸膜', N),
'cardiac': ('心', N), 'coronary': ('冠状', N), 'aortic': ('主动脉', N),
'carotid': ('颈动脉', N), 'vertebral': ('椎', N), 'cerebral': ('大脑', N),
'cerebellar': ('小脑', N), 'pontine': ('脑桥', N), 'spinal': ('脊髓', N), 'cranial': ('颅', N),
'cortical': ('皮质', N), 'thalamic': ('丘脑', N), 'hypothalamic': ('下丘脑', N),
'femoral': ('股', N), 'brachial': ('肱', N), 'radial': ('桡', N), 'ulnar': ('尺', N),
'axillary': ('腋', N), 'subclavian': ('锁骨下', N), 'axillary': ('腋', N),
'iliac': ('髂', N), 'obturator': ('闭孔', N), 'gluteal': ('臀', N), 'popliteal': ('腘', N),
'tibial': ('胫', N), 'fibular': ('腓', N), 'peroneal': ('腓', N), 'femoral': ('股', N),
'humeral': ('肱', N), 'scapular': ('肩胛', N), 'clavicular': ('锁骨', N), 'sternal': ('胸骨', N),
'intercostal': ('肋间', N), 'interventricular': ('室间', N), 'interosseous': ('骨间', N),
'intervertebral': ('椎间', N), 'interlobar': ('叶间', N), 'interlobular': ('小叶间', N),
'segmental': ('段', N), 'lobar': ('叶', N), 'cortical': ('皮质', N),
'thoracic': ('胸', N), 'cervical': ('颈', N), 'lumbar': ('腰', N), 'sacral': ('骶', N),
'coccygeal': ('尾', N), 'abdominal': ('腹', N), 'pelvic': ('盆', N), 'perineal': ('会阴', N),
'lingual': ('舌', N), 'buccal': ('颊', N), 'labial': ('唇', N), 'dental': ('牙', N), 'gingival': ('牙龈', N),
'palatal': ('腭', N), 'pharyngeal': ('咽', N), 'laryngeal': ('喉', N), 'tonsillar': ('扁桃体', N),
'nasal': ('鼻', N), 'orbital': ('眶', N), 'optic': ('视', N), 'otic': ('耳', N),
'auditory': ('听', N), 'vestibular': ('前庭', N), 'cochlear': ('耳蜗', N),
'muscular': ('肌', N), 'cutaneous': ('皮', N), 'subcutaneous': ('皮下', N),
'peritoneal': ('腹膜', N), 'mesenteric': ('肠系膜', N), 'omental': ('大网膜', N),
'adrenal': ('肾上腺', N), 'thyroid': ('甲状腺', N), 'thymic': ('胸腺', N),
'mammary': ('乳腺', N), 'uterine': ('子宫', N), 'prostatic': ('前列腺', N), 'testicular': ('睾丸', N),
'temporal': ('颞', N), 'zygomatic': ('颧', N), 'maxillary': ('上颌', N), 'mandibular': ('下颌', N),
'occipital': ('枕', N), 'parietal': ('顶', N), 'frontal': ('额', N), 'sphenoid': ('蝶', N),
'ethmoidal': ('筛', N), 'lacrimal': ('泪', N), 'mastoid': ('乳突', N), 'styloid': ('茎突', N),
'deep': ('深', N), 'superficial': ('浅', N),
'venous': ('静脉', N), 'arterial': ('动脉', N), 'arteriosus': ('动脉', N), 'venosus': ('静脉', N),

# ===== 拉丁肌名（后置） =====
'flexor': ('屈肌', MU), 'extensor': ('伸肌', MU), 'abductor': ('展肌', MU), 'adductor': ('收肌', MU),
'rotator': ('回旋肌', MU), 'levator': ('提肌', MU), 'depressor': ('降肌', MU), 'masseter': ('咬肌', MU),
'rectus': ('直肌', MU), 'obliquus': ('斜肌', MU), 'transversus': ('横肌', MU),
'semispinalis': ('半棘肌', MU), 'spinalis': ('棘肌', MU), 'longissimus': ('最长肌', MU),
'semitendinosus': ('半腱肌', MU), 'semimembranosus': ('半膜肌', MU), 'sartorius': ('缝匠肌', MU),
'gracilis': ('股薄肌', MU), 'popliteus': ('腘肌', MU), 'plantaris': ('跖肌', MU),
'soleus': ('比目鱼肌', MU), 'gastrocnemius': ('腓肠肌', MU), 'tibialis': ('胫骨肌', MU),
'fibularis': ('腓骨肌', MU), 'peroneus': ('腓骨肌', MU), 'deltoideus': ('三角肌', MU),
'trapezius': ('斜方肌', MU), 'sternocleidomastoid': ('胸锁乳突肌', MU),
'temporalis': ('颞肌', MU), 'masseteric': ('咬肌', MU), 'iliacus': ('髂肌', MU),
'psoas': ('腰肌', MU), 'piriformis': ('梨状肌', MU), 'diaphragmatic': ('膈', N),
'opponens': ('对掌肌', MU), 'lumbricals': ('蚓状肌', MU), 'interossei': ('骨间肌', MU),
'palmaris': ('掌肌', MU), 'plantaris': ('跖肌', MU), 'coracobrachialis': ('喙肱肌', MU),
'brachialis': ('肱肌', MU), 'brachioradialis': ('肱桡肌', MU), 'anconeus': ('肘肌', MU),
'supinator': ('旋后肌', MU), 'pronator': ('旋前肌', MU), 'teres': ('圆肌', MU),
'deltoid': ('三角肌', MU), 'infraspinatus': ('冈下肌', MU), 'supraspinatus': ('冈上肌', MU),
'subscapularis': ('肩胛下肌', MU), 'rhomboid': ('菱形肌', MU), 'serratus': ('锯肌', MU),
'scalene': ('斜角肌', MU), 'platysma': ('颈阔肌', MU), 'splenius': ('夹肌', MU),
'iliopsoas': ('髂腰肌', MU), 'gluteus': ('臀肌', MU), 'adductor': ('收肌', MU),

# ===== 指/趾部位词（拉丁所有格） =====
'pollicis': ('拇', N), 'hallucis': ('拇', N), 'indices': ('示指', N), 'indicis': ('示指', N),
'digitorum': ('趾', N), 'digiti': ('指', N), 'carpi': ('腕', N), 'tarsi': ('跗', N),
'cruris': ('小腿', N), 'pedis': ('足', N), 'manus': ('手', N), 'capitis': ('头', N),
'colli': ('颈', N), 'thoracis': ('胸', N), 'lumborum': ('腰', N), 'abdominis': ('腹', N),
'dorsi': ('背', N), 'oris': ('口', N), 'oculi': ('眼', N), 'nasi': ('鼻', N),
'auris': ('耳', N), 'dentis': ('牙', N), 'linguae': ('舌', N), 'femoris': ('股', N),
'tibiae': ('胫', N), 'fibulae': ('腓', N), 'humeri': ('肱', N), 'radii': ('桡', N),
'ulnae': ('尺', N), 'scapulae': ('肩胛', N), 'patellae': ('髌', N), 'calcanei': ('跟', N),
'cubiti': ('肘', N), 'genus': ('膝', N), 'nuchae': ('项', N), 'dorsi': ('背', N),

# ===== 高频多词短语（优先匹配） =====
'mitral valve': ('二尖瓣', N), 'tricuspid valve': ('三尖瓣', N), 'aortic valve': ('主动脉瓣', N),
'pulmonary valve': ('肺动脉瓣', N), 'cardiac valve': ('心瓣膜', N),
'thoracic vertebra': ('胸椎', N), 'thoracic vertebrae': ('胸椎', N),
'cervical vertebra': ('颈椎', N), 'lumbar vertebra': ('腰椎', N), 'cervical vertebrae': ('颈椎', N),
'spinal cord': ('脊髓', N), 'brain stem': ('脑干', N), 'brainstem': ('脑干', N),
'corpus callosum': ('胼胝体', N), 'pineal body': ('松果体', N), 'tuber cinereum': ('灰结节', N),
'white matter': ('白质', N), 'grey matter': ('灰质', N), 'gray matter': ('灰质', N),
'interventricular septum': ('室间隔', N), 'interatrial septum': ('房间隔', N),
'coronary sinus': ('冠状窦', N), 'portal vein': ('门静脉', N),
'inferior vena cava': ('下腔静脉', N), 'superior vena cava': ('上腔静脉', N),
'common carotid artery': ('颈总动脉', N), 'internal carotid artery': ('颈内动脉', N),
'external carotid artery': ('颈外动脉', N), 'subclavian artery': ('锁骨下动脉', N),
'vertebral artery': ('椎动脉', N), 'femoral artery': ('股动脉', N), 'popliteal artery': ('腘动脉', N),
'brachial artery': ('肱动脉', N), 'radial artery': ('桡动脉', N), 'ulnar artery': ('尺动脉', N),
'renal artery': ('肾动脉', N), 'gastric artery': ('胃动脉', N), 'hepatic artery': ('肝动脉', N),
'splenic artery': ('脾动脉', N), 'iliac artery': ('髂动脉', N),
'pulmonary artery': ('肺动脉', N), 'pulmonary vein': ('肺静脉', N),
'jugular vein': ('颈静脉', N), 'subclavian vein': ('锁骨下静脉', N), 'femoral vein': ('股静脉', N),
'portal triad': ('门管区', N), 'bile duct': ('胆管', N), 'hepatic duct': ('肝管', N),
'cystic duct': ('胆囊管', N), 'pancreatic duct': ('胰管', N),
'renal pelvis': ('肾盂', N), 'renal cortex': ('肾皮质', N), 'renal medulla': ('肾髓质', N),
'urinary bladder': ('膀胱', N), 'urethra': ('尿道', N), 'ureter': ('输尿管', N),
'small intestine': ('小肠', N), 'large intestine': ('大肠', N),
'duodenum': ('十二指肠', N), 'jejunum': ('空肠', N), 'ileum': ('回肠', N),
'caecum': ('盲肠', N), 'cecum': ('盲肠', N), 'colon': ('结肠', N), 'rectum': ('直肠', N),
'appendix': ('阑尾', N), 'gallbladder': ('胆囊', N), 'liver': ('肝', N), 'stomach': ('胃', N),
'spleen': ('脾', N), 'pancreas': ('胰', N), 'kidney': ('肾', N), 'heart': ('心脏', N),
'lung': ('肺', N), 'trachea': ('气管', N), 'oesophagus': ('食管', N), 'esophagus': ('食管', N),
'larynx': ('喉', N), 'pharynx': ('咽', N), 'tongue': ('舌', N), 'tooth': ('牙', N),
'teeth': ('牙', N), 'brain': ('脑', N), 'cerebellum': ('小脑', N), 'hippocampus': ('海马', N),
'thalamus': ('丘脑', N), 'hypothalamus': ('下丘脑', N), 'insula': ('岛叶', N),
'internal capsule': ('内囊', N), 'corona radiata': ('辐射冠', N),
'arachnoid mater': ('蛛网膜', N), 'dura mater': ('硬脑膜', N), 'pia mater': ('软脑膜', N),
'lymph node': ('淋巴结', N), 'lymph nodes': ('淋巴结', N), 'thoracic duct': ('胸导管', N),
'lymphatic vessel': ('淋巴管', N), 'lymphatic vessels': ('淋巴管', N),
'skin': ('皮肤', N), 'epidermis': ('表皮', N), 'dermis': ('真皮', N),
'hypodermis': ('皮下组织', N), 'subcutaneous tissue': ('皮下组织', N),
'mammary gland': ('乳腺', N), 'thyroid gland': ('甲状腺', N), 'adrenal gland': ('肾上腺', N),
'pituitary gland': ('垂体', N), 'parathyroid gland': ('甲状旁腺', N), 'pineal gland': ('松果体', N),
'thymus': ('胸腺', N), 'prostate': ('前列腺', N), 'testis': ('睾丸', N), 'epididymis': ('附睾', N),
'seminal vesicle': ('精囊', N), 'vas deferens': ('输精管', N), 'ductus deferens': ('输精管', N),
'penis': ('阴茎', N), 'scrotum': ('阴囊', N), 'spermatic cord': ('精索', N),
'intervertebral disk': ('椎间盘', N), 'intervertebral disc': ('椎间盘', N),
'vertebral column': ('脊柱', N), 'spinal column': ('脊柱', N),
'pectoral girdle': ('上肢带', N), 'pelvic girdle': ('下肢带', N), 'hip bone': ('髋骨', N),
'pubic symphysis': ('耻骨联合', N), 'sacroiliac joint': ('骶髂关节', N),
'knee joint': ('膝关节', N), 'hip joint': ('髋关节', N), 'shoulder joint': ('肩关节', N),
'elbow joint': ('肘关节', N), 'ankle joint': ('踝关节', N), 'wrist joint': ('腕关节', N),
'temporomandibular joint': ('颞下颌关节', N), 'atlantoaxial joint': ('寰枢关节', N),
'atlanto-occipital joint': ('寰枕关节', N),
'skeletal muscle': ('骨骼肌', N), 'smooth muscle': ('平滑肌', N), 'cardiac muscle': ('心肌', N),
'respiratory system': ('呼吸系统', N), 'digestive system': ('消化系统', N),
'nervous system': ('神经系统', N), 'cardiovascular system': ('心血管系统', N),
'lymphatic system': ('淋巴系统', N), 'endocrine system': ('内分泌系统', N),
'urinary system': ('泌尿系统', N), 'reproductive system': ('生殖系统', N),
'integumentary system': ('皮肤系统', N), 'musculoskeletal system': ('肌骨骼系统', N),
'peripheral nervous system': ('周围神经系统', N), 'central nervous system': ('中枢神经系统', N),
'autonomic nervous system': ('自主神经系统', N), 'sympathetic trunk': ('交感干', N),
'brachial plexus': ('臂丛', N), 'lumbar plexus': ('腰丛', N), 'sacral plexus': ('骶丛', N),
'cervical plexus': ('颈丛', N), 'solar plexus': ('腹腔丛', N),
'sciatic nerve': ('坐骨神经', N), 'femoral nerve': ('股神经', N), 'tibial nerve': ('胫神经', N),
'median nerve': ('正中神经', N), 'ulnar nerve': ('尺神经', N), 'radial nerve': ('桡神经', N),
'vagus nerve': ('迷走神经', N), 'phrenic nerve': ('膈神经', N), 'optic nerve': ('视神经', N),
'facial nerve': ('面神经', N), 'trigeminal nerve': ('三叉神经', N), 'glossopharyngeal nerve': ('舌咽神经', N),
'hypoglossal nerve': ('舌下神经', N), 'accessory nerve': ('副神经', N),
'olfactory nerve': ('嗅神经', N), 'oculomotor nerve': ('动眼神经', N),
'trochlear nerve': ('滑车神经', N), 'abducens nerve': ('展神经', N),
'vestibulocochlear nerve': ('前庭蜗神经', N), 'spinal nerve': ('脊神经', N),
'cranial nerve': ('脑神经', N), 'intercostal nerve': ('肋间神经', N),
}
